### ISSUE TITLE
AttributeError: module 'pip' has no attribute 'get_installed_distributions'

### ISSUE THREAD

**Issue by SergeiMinaev** [cls1991/pef#1]
```
$ pip -V
pip 18.1

```
```
$ pef bpython
Traceback (most recent call last):
  File "/media/work/target_win/venv/bin/pef", line 11, in <module>
    sys.exit(cli())
  File "/media/work/target_win/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/media/work/target_win/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/media/work/target_win/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/work/target_win/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/media/work/target_win/venv/lib/python3.7/site-packages/pef.py", line 104, in cli
    pkg = pip.get_installed_distributions()
AttributeError: module 'pip' has no attribute 'get_installed_distributions'
```

It seems like new pip doesn't support get_installed_distributions: https://github.com/pypa/pip/issues/5243

**Comment by cls1991** [comment]
@SergeiMinaev Thanks for your testing, and now it's fixed.
